#!/usr/bin/env python3
"""render-docs.py -- inline patch files into the docs pages.

A docs page that carries a patch writes a marker line:

    <!-- include: patches/0009-drm-msm-dp-force-edp-rate-to-hbr3-experiment.patch -->

This script replaces what follows (or inserts, the first time) a generated region:

    <!-- BEGIN include: <path> (generated by scripts/render-docs.py -- do not edit by hand) -->
    ...the patch, verbatim, fenced...
    <!-- END include: <path> -->

Re-running is safe: existing regions are replaced, so editing a patch and re-rendering keeps every
page in sync.  Paths are relative to the repository root.

Usage:  python3 scripts/render-docs.py [--check]
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = os.path.join(ROOT, "docs")
MARKER = re.compile(r"^<!--\s*include:\s*(\S+)\s*-->\s*$")
BEGIN = "<!-- BEGIN include: %s (generated by scripts/render-docs.py -- do not edit by hand) -->"
END = "<!-- END include: %s -->"
MAX_LINES = 900  # sanity: refuse to inline something absurd


def render_region(rel):
    path = os.path.join(ROOT, rel)
    if not os.path.exists(path):
        return None, "MISSING"
    with open(path, "r", encoding="utf-8", errors="replace") as fh:
        text = fh.read()
    lines = text.splitlines()
    if len(lines) > MAX_LINES:
        return None, "TOO LONG (%d lines)" % len(lines)
    fence = "diff" if "diff --git" in text else "text"
    body = [BEGIN % rel, "", "```" + fence, text.rstrip("\n"), "```", "", END % rel]
    return "\n".join(body), "ok"


def process(path):
    with open(path, "r", encoding="utf-8") as fh:
        lines = fh.read().split("\n")
    out, seen, changed, notes = [], set(), False, []
    i = 0
    while i < len(lines):
        line = lines[i]
        m = MARKER.match(line)
        if not m:
            out.append(line)
            i += 1
            continue
        rel = m.group(1)
        region, status = render_region(rel)
        notes.append("%s -> %s" % (rel, status))
        if region is None:
            out.append(line)
            i += 1
            continue
        seen.add(rel)
        out.append(line)
        out.append("")
        out.append(region)
        i += 1
        # skip a previously generated region, if one follows
        while i < len(lines) and lines[i].strip() == "":
            i += 1
        if i < len(lines) and lines[i].startswith("<!-- BEGIN include:"):
            while i < len(lines) and not lines[i].startswith("<!-- END include:"):
                i += 1
            if i < len(lines):
                i += 1
        changed = True
    text = "\n".join(out)
    if changed:
        with open(path, "wb") as fh:
            fh.write(text.encode("utf-8"))
    return seen, notes


def main():
    check = "--check" in sys.argv
    total = 0
    for name in sorted(os.listdir(DOCS)):
        if not name.endswith(".md"):
            continue
        path = os.path.join(DOCS, name)
        with open(path, "r", encoding="utf-8") as fh:
            src = fh.read()
        if "include:" not in src:
            continue
        if check:
            print("   %-28s has include markers" % name)
            continue
        seen, notes = process(path)
        total += len(seen)
        print("   %-28s %d patch(es): %s" % (name, len(seen), "; ".join(notes)))
    print("   %d patch(es) inlined" % total)


if __name__ == "__main__":
    main()
